image: node:16
# Workflow  Configuration
pipelines:
  branches:
    sprint-2:
      - step:
          name: Dev Build
          script:
            - npm install
            - npm run build
            - cd build
          artifacts:
            - build/**
      - step:
          name: Deploy to S3 dev Bucket
          script:
            # sync your files to S3
            - pipe: atlassian/aws-s3-deploy:0.4.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                S3_BUCKET: $AWS_DEV_BUCKET_NAME
                LOCAL_PATH: ./build/
      - step:
          name: Invalidate Cloudfront cache
          script:
            # triggering a distribution invalidation to refresh the CDN caches
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                DISTRIBUTION_ID: $CLOUDFRONT_DEV_DIST_ID

    staging:
      - step:
          name: UAT Build
          script:
            - npm install
            - npm run build-uat
            - cd build
          artifacts:
            - build/**
      - step:
          name: Deploy to S3 UAT Bucket
          script:
            # sync your files to S3
            - pipe: atlassian/aws-s3-deploy:0.4.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                S3_BUCKET: $AWS_UAT_BUCKET_NAME
                LOCAL_PATH: ./build/
      - step:
          name: Invalidate Cloudfront cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                DISTRIBUTION_ID: $CLOUDFRONT_UAT_DIST_ID
